"""Add is admin to personnel

Revision ID: 100c57b4aae1
Revises: 1e7119d3021f
Create Date: 2026-08-23 11:01:51.173057

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "100c57b4aae1"
down_revision: Union[str, Sequence[str], None] = "1e7119d3021f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "personal",
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("personal", "is_admin")
    # ### end Alembic commands ###
