"""Remove unused tables

Revision ID: 234712e32dc0
Revises: 1bd5e2454b89
Create Date: 2026-08-09 16:10:05.431003

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "234712e32dc0"
down_revision: Union[str, Sequence[str], None] = "1bd5e2454b89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("habit_tracker")
    op.drop_table("habits")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "habits",
        sa.Column("personal_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("occur", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("achieve_units", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "achieve_timeline", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("achieve_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "notify_time", postgresql.TIME(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["personal_id"],
            ["personal.id"],
            name=op.f("fk_habits_personal_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["personal_id"],
            ["personal.id"],
            name=op.f("habits_personal_id_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("habits_pkey")),
    )
    op.create_table(
        "habit_tracker",
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("completed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("ranking", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("habit_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["habit_id"], ["habits.id"], name=op.f("habit_tracker_habit_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["habit_id"], ["habits.id"], name=op.f("habit_tracker_habits_id_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("habit_tracker_pkey")),
    )
    # ### end Alembic commands ###
