services:
  db:
    image: postgres:17
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME:-tracker}
    env_file: .env
    attach: false

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "9500:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network
    attach: false

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - api
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - ./src:/api/src
      - ./tests:/api/tests
      - ./alembic.ini:/api/alembic.ini
      - ${EXTERNAL_BACKUP_PATH}:${BACKUP_PATH}
    environment:
      APP_ENV: dev
    env_file: .env
    command: uvicorn src.main:fastapi_app --host 0.0.0.0 --port 8000 --reload --reload-dir src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    command: [ "npm", "run", "dev" ]
    expose:
      - "3000"
    networks:
      - app-network
    tty: true
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/assets:/app/assets
      - ./frontend/components:/app/components
      - ./frontend/lib:/app/lib
      - ./frontend/styles:/app/styles
      - ./frontend/next.config.ts:/app/next.config.ts
    environment:
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "20"
      NODE_ENV: development
      # NODE_ENV: production
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      API_INTERNAL_URL: http://api:8000
    restart: unless-stopped

  redis:
    image: redis:8.2.5-bookworm
    container_name: redis
    command: redis-server --save 7200 1 --loglevel warning
    expose:
      - "6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data/
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: src/Dockerfile
    expose:
      - "8002"
    networks:
      - app-network
    volumes:
      - ./src:/api/src
      - ${EXTERNAL_BACKUP_PATH}:${BACKUP_PATH}
    environment:
      APP_ENV: dev
    env_file: .env
    entrypoint: celery -A src.main worker -Ofair --concurrency=4 --loglevel=INFO -E -B

networks:
  app-network:
    driver: bridge

volumes:
  pgadmin-data:
  postgres_data:
  redis-data:
