services:
  db:
    image: postgres:17 
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${DATABASE_USERNAME}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_PORT: ${DATABASE_PORT}
    env_file: .env
    attach: false

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network
    attach: false

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - api
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - ./src:/api/src
    env_file: .env
    command: uvicorn src.main:fastapi_app --host 0.0.0.0 --port 8000 --reload --reload-dir src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
    expose:
      - "3000"
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: .env

  redis:
    image: redis:8.2.5-bookworm
    container_name: redis
    command: redis-server --save 7200 1 --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data/
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: src/Dockerfile.worker
    expose:
      - "8001"
    networks:
      - app-network
    volumes:
      - ./src:/worker/src
    env_file: .env
    entrypoint: celery -A src.main worker -Ofair --concurrency=1 --loglevel=INFO -E


networks:
  app-network:
    driver: bridge


volumes:
  pgadmin-data:
  postgres_data:
  redis-data:
