"""adding in notes to ranker

Revision ID: 1bd5e2454b89
Revises: 8d5be8a782b8
Create Date: 2026-05-11 21:08:25.304118

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1bd5e2454b89"
down_revision: Union[str, Sequence[str], None] = "8d5be8a782b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ranker", sa.Column("text_events", sa.String(), nullable=True))
    op.add_column("ranker", sa.Column("text_notes", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ranker", "text_notes")
    op.drop_column("ranker", "text_events")
    # ### end Alembic commands ###
