"""update

Revision ID: 8d5be8a782b8
Revises: 8ed3a36ecd34
Create Date: 2026-05-11 21:05:33.076432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8d5be8a782b8"
down_revision: Union[str, Sequence[str], None] = "8ed3a36ecd34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "habit_tracker_habits_id_id", "habit_tracker", "habits", ["habit_id"], ["id"]
    )
    op.create_foreign_key(
        "habits_personal_id_id",
        "habits",
        "personal",
        ["personal_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("unique_personnel_email", "personal", ["email"])
    op.create_foreign_key(
        "ranker_personal_id_id",
        "ranker",
        "personal",
        ["personal_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ranker_personal_id_id", "ranker", type_="foreignkey")
    op.drop_constraint("unique_personnel_email", "personal", type_="unique")
    op.drop_constraint("habits_personal_id_id", "habits", type_="foreignkey")
    op.drop_constraint(
        "habit_tracker_habits_id_id", "habit_tracker", type_="foreignkey"
    )
    # ### end Alembic commands ###
