"""backup tracks

Revision ID: 8ed3a36ecd34
Revises: b0ee5841dd26
Create Date: 2026-05-06 21:22:43.662638

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8ed3a36ecd34"
down_revision: Union[str, Sequence[str], None] = "b0ee5841dd26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backups",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("backup_date", sa.DateTime(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("backups")
    # ### end Alembic commands ###
