"""cascade deletion

Revision ID: a73d754c162c
Revises: 6100399daf9f
Create Date: 2026-04-02 18:57:55.339385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73d754c162c'
down_revision: Union[str, Sequence[str], None] = '6100399daf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('habits_personal_id_fkey'), 'habits', type_='foreignkey')
    op.create_foreign_key("fk_habits_personal_id", 'habits', 'personal', ['personal_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ranker_personal_id_fkey'), 'ranker', type_='foreignkey')
    op.create_foreign_key("fk_ranker_personal_id", 'ranker', 'personal', ['personal_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_ranker_personal_id", 'ranker', type_='foreignkey')
    op.create_foreign_key(op.f('ranker_personal_id_fkey'), 'ranker', 'personal', ['personal_id'], ['id'])
    op.drop_constraint("fk_habits_personal_id", 'habits', type_='foreignkey')
    op.create_foreign_key(op.f('habits_personal_id_fkey'), 'habits', 'personal', ['personal_id'], ['id'])
    # ### end Alembic commands ###
