"""Simplifying backup types

Revision ID: 8bd3464819a6
Revises: 9f6f1e0db097
Create Date: 2026-09-27 21:04:27.555366

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference


# revision identifiers, used by Alembic.
revision: str = "8bd3464819a6"
down_revision: Union[str, Sequence[str], None] = "9f6f1e0db097"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="backuptype",
        new_values=["RANGED", "LOGICAL", "UPLOADED"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="backups", column_name="backup_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="backuptype",
        new_values=["FULL", "INCREMENTAL", "DIFFERENTIAL", "LOGICAL", "UPLOADED"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="backups", column_name="backup_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
