"""initial

Revision ID: 963273186392
Revises: 6ad2b7691976
Create Date: 2026-08-13 21:10:11.145176

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "963273186392"
down_revision: Union[str, Sequence[str], None] = "6ad2b7691976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "meta", "last_verified", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("meta", "total_rows")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meta",
        sa.Column("total_rows", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "meta", "last_verified", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
