"""Handling enums better

Revision ID: 9f6f1e0db097
Revises: f8a0814a170b
Create Date: 2026-09-27 20:16:34.130658

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9f6f1e0db097"
down_revision: Union[str, Sequence[str], None] = "f8a0814a170b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "FULL", "INCREMENTAL", "DIFFERENTIAL", "LOGICAL", "UPLOADED", name="backuptype"
    ).create(op.get_bind())
    sa.Enum("RUNNING", "SUCCESS", "FAILURE", "UPLOADED", name="backupstatus").create(
        op.get_bind()
    )
    sa.Enum("MANUAL", "SCHEDULED", name="backuptriggermethod").create(op.get_bind())
    op.alter_column(
        "backups",
        "trigger_method",
        existing_type=sa.VARCHAR(length=9),
        type_=sa.Enum("MANUAL", "SCHEDULED", name="backuptriggermethod"),
        existing_nullable=False,
        postgresql_using="trigger_method::backuptriggermethod",
    )
    op.alter_column(
        "backups",
        "status",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.Enum("RUNNING", "SUCCESS", "FAILURE", "UPLOADED", name="backupstatus"),
        existing_nullable=False,
        postgresql_using="status::backupstatus",
    )
    op.alter_column(
        "backups",
        "backup_type",
        existing_type=sa.VARCHAR(length=12),
        type_=sa.Enum(
            "FULL",
            "INCREMENTAL",
            "DIFFERENTIAL",
            "LOGICAL",
            "UPLOADED",
            name="backuptype",
        ),
        existing_nullable=False,
        postgresql_using="backup_type::backuptype",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backups",
        "backup_type",
        existing_type=sa.Enum(
            "FULL",
            "INCREMENTAL",
            "DIFFERENTIAL",
            "LOGICAL",
            "UPLOADED",
            name="backuptype",
        ),
        type_=sa.VARCHAR(length=12),
        existing_nullable=False,
    )
    op.alter_column(
        "backups",
        "status",
        existing_type=sa.Enum(
            "RUNNING", "SUCCESS", "FAILURE", "UPLOADED", name="backupstatus"
        ),
        type_=sa.VARCHAR(length=8),
        existing_nullable=False,
    )
    op.alter_column(
        "backups",
        "trigger_method",
        existing_type=sa.Enum("MANUAL", "SCHEDULED", name="backuptriggermethod"),
        type_=sa.VARCHAR(length=9),
        existing_nullable=False,
    )
    sa.Enum("MANUAL", "SCHEDULED", name="backuptriggermethod").drop(op.get_bind())
    sa.Enum("RUNNING", "SUCCESS", "FAILURE", "UPLOADED", name="backupstatus").drop(
        op.get_bind()
    )
    sa.Enum(
        "FULL", "INCREMENTAL", "DIFFERENTIAL", "LOGICAL", "UPLOADED", name="backuptype"
    ).drop(op.get_bind())
    # ### end Alembic commands ###
