name: Production Ready Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Application
        run: docker compose -f docker-compose.prod-test.yaml up -d

      - name: Wait time
        run: sleep 12

      - name: Upgrade Database
        run: docker compose -f docker-compose.prod-test.yaml exec api alembic -c /api/alembic.ini upgrade head

      - name: Frontend check
        run: |
          curl --fail http://localhost/login

      - name: API check
        run: |
          curl --fail http://localhost/api/docs

      - name: Celery Task check
        run: |
          curl http://localhost/api/v1/tasks/simulate-task
          curl --fail http://localhost/api/v1/tasks/simulate-task
